{"name": "test_appointment_with_past_date", "status": "failed", "statusDetails": {"message": "AssertionError: BUG: Appointment got confirmed with a past date.\nassert not True", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"9816ba21a70869adceb82811200637d9\")>\n\n    def test_appointment_with_past_date(browser):\n        login = LoginPage(browser)\n        login.do_login(\"John Doe\", \"ThisIsNotAPassword\")\n    \n        appointment = AppointmentPage(browser)\n        appointment.make_appointment(\n            facility=\"Tokyo CURA Healthcare Center\",\n            readmission=False,\n            program=\"Medicaid\",\n            visit_date=\"01/01/2020\",  # Past date\n            comment=\"Testing with past date\"\n        )\n    \n        # Check if confirmation is wrongly shown\n        try:\n            confirmed = appointment.is_appointment_confirmed()\n>           assert not confirmed, \"BUG: Appointment got confirmed with a past date.\"\nE           AssertionError: BUG: Appointment got confirmed with a past date.\nE           assert not True\n\ntests/test_invalid_appointment.py:43: AssertionError"}, "start": 1751879031167, "stop": 1751879037599, "uuid": "5fb80bd4-79d3-4834-b397-c8a54d1ee927", "historyId": "5f1cc0dd73f6c4feb6866ced5210898a", "testCaseId": "5f1cc0dd73f6c4feb6866ced5210898a", "fullName": "tests.test_invalid_appointment#test_appointment_with_past_date", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_invalid_appointment"}, {"name": "host", "value": "shahabas-LOQ-15IRX9"}, {"name": "thread", "value": "1304075-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_invalid_appointment"}]}